/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Fernando
 */
public class Cliente1V2 extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    /*
    Operador es un valor de tipo String que cambiara segun el operador que seleccionemos en nuestra interfaz para 
   `poder interpretarlo en el servidor
    */
    String operador=null;
    Socket clienteSocket;
    int c=0;
    public Cliente1V2() {
        initComponents();
        b1.setEnabled(false);
        
      b2.setEnabled(false);
      b3.setEnabled(false);
      b4.setEnabled(false);
      b5.setEnabled(false);
      b6.setEnabled(false);
      b7.setEnabled(false);
      b8.setEnabled(false);
      b9.setEnabled(false);
      b10.setEnabled(false);
      bSuma.setEnabled(false);
      bResta.setEnabled(false);
      bDivi.setEnabled(false);
      bMulti.setEnabled(false);
      bRaiz.setEnabled(false);
      bDeci.setEnabled(false);
      jbNega.setEnabled(false);
      bEnviar.setEnabled(false);
      t1.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSuma = new javax.swing.JButton();
        bResta = new javax.swing.JButton();
        bMulti = new javax.swing.JButton();
        bDivi = new javax.swing.JButton();
        bRaiz = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        bEnviar = new javax.swing.JButton();
        jbNega = new javax.swing.JButton();
        bDeci = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtIP = new javax.swing.JTextField();
        jtServer = new javax.swing.JTextField();
        jbConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSuma.setText("Sumar(+)");
        bSuma.setMaximumSize(new java.awt.Dimension(110, 50));
        bSuma.setMinimumSize(new java.awt.Dimension(110, 50));
        bSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumaActionPerformed(evt);
            }
        });
        getContentPane().add(bSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 90, 75));

        bResta.setText("Restar(-)");
        bResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRestaActionPerformed(evt);
            }
        });
        getContentPane().add(bResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 75));

        bMulti.setText("Multi(*)");
        bMulti.setMaximumSize(new java.awt.Dimension(100, 20));
        bMulti.setMinimumSize(new java.awt.Dimension(100, 20));
        bMulti.setPreferredSize(new java.awt.Dimension(110, 20));
        bMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiActionPerformed(evt);
            }
        });
        getContentPane().add(bMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 90, 75));

        bDivi.setText("División(/)");
        bDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiviActionPerformed(evt);
            }
        });
        getContentPane().add(bDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, 75));

        bRaiz.setText("Raiz(√)");
        bRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRaizActionPerformed(evt);
            }
        });
        getContentPane().add(bRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 90, 75));

        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(75, 75));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(75, 75));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(75, 75));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(75, 75));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(75, 75));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(75, 75));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(75, 75));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(75, 75));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(75, 75));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        b10.setText("0");
        b10.setPreferredSize(new java.awt.Dimension(75, 75));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        t1.setPreferredSize(new java.awt.Dimension(75, 50));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 470, -1));

        bEnviar.setText("Enviar");
        bEnviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(bEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 90, 75));

        jbNega.setText("Negativo(-)");
        jbNega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNegaActionPerformed(evt);
            }
        });
        getContentPane().add(jbNega, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 90, 75));

        bDeci.setText("Decimal(.)");
        bDeci.setMaximumSize(new java.awt.Dimension(100, 20));
        bDeci.setMinimumSize(new java.awt.Dimension(100, 20));
        bDeci.setPreferredSize(new java.awt.Dimension(110, 20));
        bDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeciActionPerformed(evt);
            }
        });
        getContentPane().add(bDeci, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 90, 75));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("CONEXIONES");

        jLabel2.setText("Enderezo IP:");

        jLabel3.setText("Porto do Servidor:");

        jtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIPActionPerformed(evt);
            }
        });

        jbConectar.setText("Conectar");
        jbConectar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtServer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(jtServer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 220, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiActionPerformed
        /*
        Boton de multiplicar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 103 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t1.setText(" * ");
        operador="103";
       
    }//GEN-LAST:event_bMultiActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        
            t1.setText(t1.getText()+"1");
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
            
            t1.setText(t1.getText()+"2");
            jbNega.setEnabled(false);
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
            t1.setText(t1.getText()+"3");
            jbNega.setEnabled(false);
        
        
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        
            t1.setText(t1.getText()+"4");
            jbNega.setEnabled(false);
        
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        
            t1.setText(t1.getText()+"5");
            jbNega.setEnabled(false);

    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       
            t1.setText(t1.getText()+"6");
            jbNega.setEnabled(false);
        
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        
            t1.setText(t1.getText()+"7");
            jbNega.setEnabled(false);
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        
            t1.setText(t1.getText()+"8");
            jbNega.setEnabled(false);
        
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       
            t1.setText(t1.getText()+"9");
            jbNega.setEnabled(false);
       
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        
            t1.setText(t1.getText()+"0");
            jbNega.setEnabled(false);
       
    }//GEN-LAST:event_b10ActionPerformed

    private void bSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumaActionPerformed
        /*
        Boton de sumar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 101 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t1.setText(t1.getText()+" + ");
        operador="101";
        
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bSumaActionPerformed

    private void bRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRestaActionPerformed
        /*
        Boton de restar muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 102 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t1.setText(t1.getText()+" - ");
        operador="102";
        
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bRestaActionPerformed

    private void bDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiviActionPerformed
        /*
        Boton de dividir muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 104 e impide que se puedan dar a los otros botones una vez dado este.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t1.setText(t1.getText()+" / ");
        operador="104";
        
        jbNega.setEnabled(true);
    }//GEN-LAST:event_bDiviActionPerformed

    private void bRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRaizActionPerformed
        /*
        Boton de la raiz muestra la operación que vamos a realizar en un TextView, mete su codigo en el operador 
        para tratarlo en el servidor en su caso es 105 e impide que se puedan dar a los otros botones una vez dado este, 
        además a diferencia de los otros, tambien impide que se pueda escribir en el ultimo TextView porque la raiz solo 
        necesita un valor.
        */
        bSuma.setEnabled(false);
        bMulti.setEnabled(false);
        bResta.setEnabled(false);
        bDivi.setEnabled(false);
        bRaiz.setEnabled(false);
        t1.setText(t1.getText()+" √ ");
        operador="105";
        t1.setEditable(false);
        t1.setEnabled(false);
        
        
    }//GEN-LAST:event_bRaizActionPerformed

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        try{
            /*
            Abrimos el socket del cliente y establecemos la conexión con el host del servidor
            ademas creamos ya nuestros Inputs y Outputs Stream que usaremos
            */
            
            
            InputStream is = clienteSocket.getInputStream();
            OutputStream os= clienteSocket.getOutputStream();
            
            
            os.write(t1.getText().getBytes());
            
            
            byte[]result=new byte[100];
            is.read(result);
            t1.setText(new String (result));
            
            System.out.println(new String(result));
            /*
            Despues cerramos el socket.
            */
            
            
            }catch (IOException e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_bEnviarActionPerformed

    private void jbNegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNegaActionPerformed
       
                t1.setText(t1.getText()+"-");
            
             
        
       
        
    }//GEN-LAST:event_jbNegaActionPerformed

    private void bDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeciActionPerformed
        t1.setText(t1.getText()+".");
    }//GEN-LAST:event_bDeciActionPerformed

    private void jtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIPActionPerformed
        
    }//GEN-LAST:event_jtIPActionPerformed

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
      /*
        Hace todos los botones funcionales para trabajar con el y crea la conexion o la cierra si el boton ya ha sido ejecutado
      */
        
       b1.setEnabled(true);
      b2.setEnabled(true);
      b3.setEnabled(true);
      b4.setEnabled(true);
      b5.setEnabled(true);
      b6.setEnabled(true);
      b7.setEnabled(true);
      b8.setEnabled(true);
      b9.setEnabled(true);
      b10.setEnabled(true);
      bSuma.setEnabled(true);
      bResta.setEnabled(true);
      bDivi.setEnabled(true);
      bMulti.setEnabled(true);
      bRaiz.setEnabled(true);
      bDeci.setEnabled(true);
      jbNega.setEnabled(true);
      bEnviar.setEnabled(true);
      t1.setEnabled(true);
      jtIP.setEnabled(false);
      jtServer.setEnabled(false);
      try{
            /*
            Abrimos el socket del cliente y establecemos la conexión con el host del servidor
            ademas creamos ya nuestros Inputs y Outputs Stream que usaremos
            */
            
            
            if(c==0){
            System.out.println("Creando socket cliente");
            clienteSocket=new Socket();
            System.out.println("Estableciendo la conexion");
            InetSocketAddress addr=new InetSocketAddress(jtIP.getText(),Integer.parseInt(jtServer.getText()));
            clienteSocket.connect(addr);
            System.out.println("conexion hecha");
            c+=1;
            jbConectar.setText("Desconectar");
            
            }else{
            System.out.println("Terminado");
            clienteSocket.close();
            System.exit(0);
            }
      
      }catch (IOException e) {
                
                
                e.printStackTrace();
        }
    }//GEN-LAST:event_jbConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente1V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente1V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente1V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente1V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente1V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bDeci;
    private javax.swing.JButton bDivi;
    private javax.swing.JButton bEnviar;
    private javax.swing.JButton bMulti;
    private javax.swing.JButton bRaiz;
    private javax.swing.JButton bResta;
    private javax.swing.JButton bSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbNega;
    private javax.swing.JTextField jtIP;
    private javax.swing.JTextField jtServer;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
